<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Details Kemeja Rivet</name>
   <tag></tag>
   <elementGuidId>f80684a3-70a7-4ff8-8931-06a2567342d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.products-items-65e134f2a79b2.products-items-65e134f2b53ad > ul.product-items.widget-product-carousel.slick-initialized.slick-slider > div.slick-list.draggable > div.slick-track > div.slick-slide.slick-current.slick-active > div > li.product-item > div.product-item-info > div.product-item-details > strong.product-item-name > a.product-item-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[14]/div/div/div/div/div/div[2]/ul/div/div/div[9]/div/li/div/div/strong/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Details Kemeja Rivet&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ecb6297-03f3-43b4-a7c4-b2a6d5fe675b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Details Kemeja Rivet</value>
      <webElementGuid>86ced21f-7b90-40cb-9a8e-3487c854e1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.matahari.com/103945341.html</value>
      <webElementGuid>109d8989-ed24-4bff-9789-cebda4b4b056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-item-link</value>
      <webElementGuid>50f4b93a-b178-4b79-bcf9-61cd470dbc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>87d9ac81-0300-4e2e-a42e-3a7c30b1f481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Details Kemeja Rivet</value>
      <webElementGuid>120b2084-b193-4aa6-bae3-0edc92da2713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;flex-basis-50 lazyloaded&quot;]/div[@class=&quot;row-full-width-inner lazyloaded&quot;]/div[1]/div[@class=&quot;widget block block-static-block&quot;]/div[@class=&quot;lazyloaded&quot;]/div[@class=&quot;row-full-width-inner lazyloaded&quot;]/div[@class=&quot;products-items-65e134f2a79b2 products-items-65e134f2b53ad&quot;]/ul[@class=&quot;product-items widget-product-carousel slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-current slick-active&quot;]/div[1]/li[@class=&quot;product-item&quot;]/div[@class=&quot;product-item-info&quot;]/div[@class=&quot;product-item-details&quot;]/strong[@class=&quot;product-item-name&quot;]/a[@class=&quot;product-item-link&quot;]</value>
      <webElementGuid>34652649-4144-4d28-87f8-1ab5045da4b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[14]/div/div/div/div/div/div[2]/ul/div/div/div[9]/div/li/div/div/strong/a</value>
      <webElementGuid>1b3364ef-4c1d-4ccc-802d-e04d5b522202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Details Kemeja Rivet')]</value>
      <webElementGuid>ec391f57-caa3-47f9-a2e5-00dd1ba65a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[6]/following::a[1]</value>
      <webElementGuid>e82e2270-b41b-4f1b-b504-0eb4b1d0971a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambahkan ke Daftar Keinginan'])[105]/following::a[1]</value>
      <webElementGuid>3c02c7fd-5912-45ea-bc87-2db23b6baf22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 139,930'])[1]/preceding::a[1]</value>
      <webElementGuid>6cd3b100-8940-41ec-9959-8969427a963a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 199,900'])[5]/preceding::a[1]</value>
      <webElementGuid>681eea07-f4b0-457e-ac19-345d4a04fcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Details Kemeja Rivet']/parent::*</value>
      <webElementGuid>99526354-efae-4d3c-acfb-e539c8f78605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.matahari.com/103945341.html')])[2]</value>
      <webElementGuid>a12eed4f-264d-4053-ad4c-205279d8fba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/ul/div/div/div[9]/div/li/div/div/strong/a</value>
      <webElementGuid>8e190ed6-d424-4cfd-83a5-35c23bacd40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Details Kemeja Rivet' and @href = 'https://www.matahari.com/103945341.html' and (text() = 'Details Kemeja Rivet' or . = 'Details Kemeja Rivet')]</value>
      <webElementGuid>dabcac6e-684f-4b07-be4b-af015826e10c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
